'use strict';
const path=require('path');global.window=global;const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/core/state.js','js/core/enemy.js','js/core/battle.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data,assert=(x,m)=>{if(!x)throw new Error(m)};
assert(D.V12_CARD_IDS.length===24,`v12 cards ${D.V12_CARD_IDS.length}`);assert(D.V12_RELIC_IDS.length===12,`v12 relics ${D.V12_RELIC_IDS.length}`);assert(D.V12_PROTOCOL_IDS.length===6,`v12 protocols ${D.V12_PROTOCOL_IDS.length}`);assert(D.V12_TRAIT_IDS.length===4,`v12 traits ${D.V12_TRAIT_IDS.length}`);assert(Object.keys(D.ENEMY_BEHAVIORS).length===16,'behavior count');
const rewards=new Set(D.UNLOCKS.flatMap(u=>u.reward||[]));for(const id of [...D.V12_CARD_IDS,...D.V12_RELIC_IDS,...D.V12_PROTOCOL_IDS,...D.V12_TRAIT_IDS])assert(rewards.has(id),`no unlock route ${id}`);for(const id of Object.keys(D.ENEMY_BEHAVIORS))assert(D.UNLOCKS.some(u=>(u.reward||[]).includes(id)),`no behavior discovery entry ${id}`);
let migrated=BL.Store.mergeDefaults({version:11,deck:[...D.DEFAULT_DECK],unlockedCards:{},unlockedRelics:{},unlockedBehaviors:{bh_brutal_pulse:true}});assert(migrated.version===30,'migration version');assert(migrated.unlockedBehaviors.bh_brutal_pulse,'behavior migration');
// Combination discovery and activation.
BL.Store.state=BL.Store.defaultState();let s=BL.Store.state;s.unlockedTraits.giant=true;s.unlockedTraits.berserk=true;s.enemy.traits.giant=true;s.enemy.traits.berserk=true;let found=BL.Enemy.detectBehaviorDiscoveries(s);assert(found.includes('暴虐脈動'),'behavior discovery missing');assert(s.unlockedBehaviors.bh_brutal_pulse,'behavior unlock missing');let e=BL.Enemy.effective(s,false);assert(e.behaviors.includes('bh_brutal_pulse'),'behavior not active');
// Dedicated low-HP action actually changes enemy behavior without duplicating cards.
s.deck=Array(10).fill('deep_guard');let r=BL.Battle.create(false);assert(!r.error,'behavior battle start');let b=BL.Battle.current;b.enemy.hp=Math.floor(b.enemy.maxHp/2);const atkBefore=b.enemy.atk;BL.Battle.play(0);assert(BL.Battle.current&&BL.Battle.current.enemy.atk===atkBefore+3,'brutal pulse did not trigger');assert(BL.Battle.invariant().ok,'behavior broke card ownership');BL.Battle.retire();
// Multiple behaviors can coexist.
BL.Store.state=BL.Store.defaultState();s=BL.Store.state;for(const id of ['giant','berserk','fast']){s.unlockedTraits[id]=true;s.enemy.traits[id]=true;}BL.Enemy.detectBehaviorDiscoveries(s);e=BL.Enemy.effective(s,false);assert(e.behaviors.length>=3,'multi behavior combination failed');
console.log('PASS expansion12_systems.test.js');
