'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');global.window=global;const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const m of html.matchAll(/<script src="([^"?]+)/g)){const f=m[1];if(f.includes('/ui/')||f.endsWith('app.js'))continue;require(path.join(root,f));}
const BL=global.BuildLab,D=BL.Data;
assert.deepEqual({cards:Object.keys(D.CARDS).length,chars:Object.keys(D.CHARACTERS).length,styles:Object.keys(D.CHARACTER_STYLES).length,relics:Object.keys(D.RELICS).length,protocols:Object.keys(D.PROTOCOLS).length,tunings:Object.keys(D.TUNINGS).length,traits:Object.keys(D.TRAITS).length,behaviors:Object.keys(D.ENEMY_BEHAVIORS).length,arcana:Object.keys(D.ARCANA).length,unlocks:D.UNLOCKS.length},{cards:541,chars:40,styles:101,relics:411,protocols:169,tunings:76,traits:97,behaviors:120,arcana:22,unlocks:666});
assert.equal(D.V26_CARD_IDS.length,38);assert.equal(Object.keys(D.DUAL_FACE_CARDS).filter?Object.keys(D.DUAL_FACE_CARDS).filter(id=>id.startsWith('v26_')).length:Object.keys(D.DUAL_FACE_CARDS).length,8);assert.equal(D.V26_CHARACTER_IDS.length,3);assert.equal(D.V26_STYLE_IDS.length,9);assert.equal(D.V26_RELIC_IDS.length,20);assert.equal(D.V26_PROTOCOL_IDS.length,12);assert.equal(D.V26_TUNING_IDS.length,10);assert.equal(D.V26_TRAIT_IDS.length,10);assert.equal(D.V26_BEHAVIOR_IDS.length,20);
const nums=Object.values(D.ARCANA).map(a=>a.number).sort((a,b)=>a-b);assert.deepEqual(nums,[...Array(22).keys()]);for(const a of Object.values(D.ARCANA)){assert(a.upright?.desc&&a.reversed?.desc,'arcana side missing '+a.id);assert.notEqual(a.upright.desc,a.reversed.desc,'arcana sides identical '+a.id);assert(D.arcanaConditionText(a.id)!=='解放条件未登録','arcana condition missing '+a.id);}
for(const id of Object.keys(D.TRAITS))assert(D.traitConditionText(id)!=='発見条件未登録','trait condition missing '+id);
const rewarded=new Set(D.UNLOCKS.flatMap(u=>u.reward||[]));for(const id of [...D.V26_CARD_IDS,...D.V26_CHARACTER_IDS,...D.V26_STYLE_IDS,...D.V26_RELIC_IDS,...D.V26_PROTOCOL_IDS,...D.V26_TUNING_IDS,...D.V26_TRAIT_IDS,...D.V26_BEHAVIOR_IDS])assert(rewarded.has(id),'v26 item has no unlock route '+id);
// 二面カードは実体単位で一方向変化し、総所有数を変えない。
BL.Store.state=BL.Store.defaultState();BL.Store.state.unlockedCards.v26_dual_border=true;BL.Store.state.deck=Array(10).fill('v26_dual_border');BL.Store.state.enemy.hp=20;BL.Store.state.enemy.atk=.1;let st=BL.Battle.create(false);assert(!st.error);const total0=BL.Battle.invariant().count;BL.Battle.current.player.block=12;const uid=BL.Battle.current.prompt[0].uid;BL.Battle.play(0);if(BL.Battle.current){const inst=BL.Battle.allOwnedInstances().find(x=>x.uid===uid);assert(inst&&inst.face==='back','dual face did not transform');BL.Battle.current.player.block=0;assert.equal(D.resolveDualFaceCard(inst,BL.Battle.current).face,'back','dual face reverted');assert.equal(BL.Battle.invariant().count,total0,'dual transform changed ownership');BL.Battle.retire();}
// 完全同一説明の再発を簡易監査。
for(const [label,obj] of [['cards',D.CARDS],['relics',D.RELICS],['protocols',D.PROTOCOLS]]){const m=new Map();for(const [id,x] of Object.entries(obj)){const d=(x.desc||'').trim();if(!d)continue;if(!m.has(d))m.set(d,[]);m.get(d).push(id);}const dup=[...m.values()].filter(x=>x.length>1&&x.some(id=>id.startsWith('v26_')));assert.equal(dup.length,0,`${label} v26 duplicate descriptions ${JSON.stringify(dup)}`);}
console.log('PASS expansion26_systems.test.js');
