'use strict';
const path=require('path');global.window=global;const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/core/state.js','js/core/enemy.js','js/core/battle.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data,assert=(x,m)=>{if(!x)throw new Error(m)};
assert(D.V11_CARD_IDS.length===24,`v11 cards ${D.V11_CARD_IDS.length}`);assert(D.V11_RELIC_IDS.length===12,`v11 relics ${D.V11_RELIC_IDS.length}`);assert(D.V11_PROTOCOL_IDS.length===6,`v11 protocols ${D.V11_PROTOCOL_IDS.length}`);assert(D.V11_TRAIT_IDS.length===4,`v11 traits ${D.V11_TRAIT_IDS.length}`);assert(Object.keys(D.CARD_CONVERSIONS).length===7,'conversion count');
const rewards=new Set(D.UNLOCKS.flatMap(u=>u.reward||[]));for(const id of [...D.V11_CARD_IDS,...D.V11_RELIC_IDS,...D.V11_PROTOCOL_IDS])assert(rewards.has(id),`no unlock route ${id}`);for(const id of D.V11_TRAIT_IDS)assert(D.UNLOCKS.some(u=>(u.reward||[]).includes(id)),`no trait route ${id}`);
let s=BL.Store.mergeDefaults({version:10,boss2Defeated:true,claimedUnlocks:{boss2_clear:true},deck:[...D.DEFAULT_DECK],unlockedCards:{},unlockedRelics:{}});assert(s.version===26,'migration version');assert(s.unlockedSystems.card_conversion,'boss2 old save conversion system');
// split conversion makes a single-hit card multihit and preserves ownership
BL.Store.state=BL.Store.defaultState();BL.Store.state.unlockedSystems.card_conversion=true;BL.Store.state.deck=Array(10).fill('blood_blade');BL.Store.state.cardConversions={blood_blade:'split'};let r=BL.Battle.create(false);assert(!r.error,'split start');const before=BL.Battle.current.enemy.hp;BL.Battle.play(0);const after=BL.Battle.current?BL.Battle.current.enemy.hp:0;assert(before-after>0,'split no damage');assert(BL.Battle.invariant().ok,'split ownership');BL.Battle.retire();
// bulwark conversion adds block and tag
BL.Store.state=BL.Store.defaultState();BL.Store.state.unlockedSystems.card_conversion=true;BL.Store.state.deck=Array(10).fill('double_strike');BL.Store.state.cardConversions={double_strike:'bulwark'};r=BL.Battle.create(false);assert(!r.error,'bulwark start');BL.Battle.play(0);assert(D.getCardTags(BL.Store.state,'double_strike').includes('耐久'),'virtual tag missing');
console.log('PASS expansion11_systems.test.js');
