'use strict';
const path=require('path');global.window=global;global.localStorage={getItem(){return null},setItem(){},removeItem(){}};
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/core/state.js','js/core/enemy.js','js/core/battle.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data;const assert=(x,m)=>{if(!x)throw new Error(m)};
assert(D.V14_CARD_IDS.length===30,`v14 cards ${D.V14_CARD_IDS.length}`);assert(D.V14_RELIC_IDS.length===14,`v14 relics ${D.V14_RELIC_IDS.length}`);assert(D.V14_PROTOCOL_IDS.length===8,`v14 protocols ${D.V14_PROTOCOL_IDS.length}`);
assert(Object.keys(D.V14_RELIC_RULES||{}).length===14,'v14 relic rule count');assert(Object.keys(D.V14_PROTOCOL_RULES||{}).length===8,'v14 protocol rule count');
let s=BL.Store.mergeDefaults({version:13,deck:[...D.DEFAULT_DECK],unlockedCards:{},unlockedRelics:{},ui:{cardMobileLimit:120,relicMobileLimit:96}});assert(s.version===30,'v13->current migration');assert(s.ui.cardMobileLimit===120&&s.ui.relicMobileLimit===96,'mobile list state migration');
// 捨て札研究IIIのアンロック経路。
s=BL.Store.defaultState();const discardIds=Object.keys(D.CARDS).filter(id=>D.CARDS[id].tags.includes('捨て札')&&s.unlockedCards[id]).slice(0,5);assert(discardIds.length>=5,'not enough unlocked discard cards for route');s.deck=[...discardIds,...D.DEFAULT_DECK].slice(0,10);BL.Store.state=s;const got=BL.Unlock.processWinUnlocks(s,{isBoss:false,enemy:{traits:[],behaviors:[]}});for(const id of ['sediment_blade','residue_bastion','cinder_offcut','salvage_jab'])assert(s.unlockedCards[id],`v14 discard reward missing ${id}`);assert(s.unlockedRelics.v14_discard_core,'v14 discard relic missing');assert(got.length>0,'v14 unlock result missing');
// v0.14ルールテーブルで追加遺物・プロトコルが実戦可能。
s=BL.Store.defaultState();for(const id of D.V14_CARD_IDS)s.unlockedCards[id]=true;for(const id of D.V14_RELIC_IDS)s.unlockedRelics[id]=true;for(const id of D.V14_PROTOCOL_IDS)s.unlockedProtocols[id]=true;s.deck=Array(10).fill('v14_toxic_barrage');s.relics=['v14_multi_status'];s.protocol='v14_p_multi_status';s.enemy.hp=20;s.enemy.atk=1;BL.Store.state=s;const r=BL.Battle.create(false);assert(!r.error,'v14 battle create');BL.Battle.play(0);if(BL.Battle.current){assert(BL.Battle.invariant().ok,'v14 rule ownership');BL.Battle.retire();}
console.log('PASS expansion14_systems.test.js');
