'use strict';
const path=require('path');global.window=global;const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/data/expansion17.js','js/data/expansion18.js','js/data/expansion19.js','js/data/runes.js','js/data/arcana.js','js/data/expansion20.js','js/data/balance22.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/data/unlocks17.js','js/data/unlocks18.js','js/data/unlocks19.js','js/data/unlocks20.js','js/core/state.js','js/core/enemy.js','js/core/battle.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data,assert=(x,m)=>{if(!x)throw new Error(m)};
assert(D.V20_CHARACTER_IDS.length===6,`v20 chars ${D.V20_CHARACTER_IDS.length}`);assert(D.V20_STYLE_IDS.length===18,`v20 styles ${D.V20_STYLE_IDS.length}`);assert(D.V20_RELIC_IDS.length===30,`v20 relics ${D.V20_RELIC_IDS.length}`);assert(D.V20_PROTOCOL_IDS.length===15,`v20 protocols ${D.V20_PROTOCOL_IDS.length}`);assert(D.V20_TUNING_IDS.length===8,`v20 tunings ${D.V20_TUNING_IDS.length}`);assert(D.V20_TRAIT_IDS.length===8,`v20 traits ${D.V20_TRAIT_IDS.length}`);assert(D.V20_BEHAVIOR_IDS.length===12,`v20 behaviors ${D.V20_BEHAVIOR_IDS.length}`);assert(Object.keys(D.RUNES).length===12,'rune count');assert(Object.keys(D.ARCANA).length===22,'arcana count');
let s=BL.Store.mergeDefaults({version:19,deck:[...D.DEFAULT_DECK],unlockedCards:{},unlockedRelics:{}});assert(s.version===26,'v19->v20 migration failed');
s=BL.Store.mergeDefaults({version:19,boss4Defeated:true,deck:[...D.DEFAULT_DECK],unlockedCards:{},unlockedRelics:{}});assert(s.unlockedSystems.rune&&s.unlockedSystems.arcana,'boss4 old save systems');for(const id of ['rune_force','rune_ward','rune_venom','rune_barrage','rune_echo','rune_rebirth'])assert(s.unlockedRunes[id],`starter rune migration ${id}`);for(const id of ['arcana_magician','arcana_chariot','arcana_strength','arcana_wheel','arcana_justice','arcana_temperance'])assert(s.unlockedArcana[id],`starter arcana migration ${id}`);
BL.Store.state=BL.Store.defaultState();Object.assign(BL.Store.state,{boss3Defeated:true,claimedUnlocks:{v20_integration_trial:true},defeatedTraits:{v19_omega:true}});assert(BL.Unlock.boss4Available(BL.Store.state),'boss4 availability');
// Rune / Arcana actually amplify card output.
function damageWith(setup){BL.Store.state=BL.Store.defaultState();BL.Store.state.deck=Array(10).fill('blood_blade');setup?.(BL.Store.state);let out=null;BL.Battle.onEnd=r=>out=r;const r=BL.Battle.create(false);assert(!r.error,'battle start');const b=BL.Battle.current,before=b.enemy.hp;BL.Battle.play(0);const dealt=before-(BL.Battle.current?BL.Battle.current.enemy.hp:out.battle.enemy.hp);if(BL.Battle.current)BL.Battle.retire();return dealt;}
const base=damageWith();const rune=damageWith(s=>{s.unlockedRunes.rune_force=true;s.cardRunes.blood_blade='rune_force';});const arc=damageWith(s=>{s.unlockedArcana.arcana_chariot=true;s.arcana={id:'arcana_chariot',orientation:'reversed'};});assert(rune>base,`rune multiplier not applied ${base}->${rune}`);assert(arc>base,`arcana multiplier not applied ${base}->${arc}`);
console.log('PASS expansion20_systems.test.js', {chars:D.V20_CHARACTER_IDS.length,styles:D.V20_STYLE_IDS.length,relics:D.V20_RELIC_IDS.length,protocols:D.V20_PROTOCOL_IDS.length,tunings:D.V20_TUNING_IDS.length,traits:D.V20_TRAIT_IDS.length,behaviors:D.V20_BEHAVIOR_IDS.length,runes:Object.keys(D.RUNES).length,arcana:Object.keys(D.ARCANA).length});
