 'use strict';
const path=require('path');global.window=global;global.localStorage={getItem(){return null},setItem(){},removeItem(){}};
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/data/expansion17.js','js/data/expansion18.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/data/unlocks17.js','js/data/unlocks18.js','js/core/state.js','js/core/enemy.js','js/core/battle.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data;const assert=(x,m)=>{if(!x)throw new Error(m)};
assert(D.V17_CARD_IDS.length===24,`v17 cards ${D.V17_CARD_IDS.length}`);assert(D.V17_RELIC_IDS.length===12,`v17 relics ${D.V17_RELIC_IDS.length}`);assert(D.V17_PROTOCOL_IDS.length===6,`v17 protocols ${D.V17_PROTOCOL_IDS.length}`);
for(const id of D.V17_RELIC_IDS)assert(D.V14_RELIC_RULES[id],`v17 relic rule missing ${id}`);for(const id of D.V17_PROTOCOL_IDS)assert(D.V14_PROTOCOL_RULES[id],`v17 protocol rule missing ${id}`);
let s=BL.Store.defaultState();const ids=Object.keys(D.CARDS).filter(id=>s.unlockedCards[id]&&(D.getCardTags?D.getCardTags(s,id):D.CARDS[id].tags).includes('捨て札')).slice(0,6);assert(ids.length===6,'need six unlocked discard cards');s.deck=[...ids,...D.DEFAULT_DECK].slice(0,10);BL.Store.state=s;const got=BL.Unlock.processWinUnlocks(s,{isBoss:false,enemy:{traits:[],behaviors:[]}});for(const id of ['v17_residue_spear','v17_echo_fort','v17_cinder_cache','v17_reclaim_cut'])assert(s.unlockedCards[id],`v17 discard reward missing ${id}`);assert(s.unlockedRelics.v17_discard_focus,'v17 relic reward missing');assert(s.unlockedProtocols.v17_p_discard,'v17 protocol reward missing');assert(got.length>0,'v17 unlock results missing');
s=BL.Store.defaultState();for(const id of D.V17_CARD_IDS)s.unlockedCards[id]=true;for(const id of D.V17_RELIC_IDS)s.unlockedRelics[id]=true;for(const id of D.V17_PROTOCOL_IDS)s.unlockedProtocols[id]=true;s.deck=Array(10).fill('v17_venom_fan');s.relics=['v17_multi_focus'];s.protocol='v17_p_multi';s.enemy.hp=30;s.enemy.atk=1;BL.Store.state=s;const r=BL.Battle.create(false);assert(!r.error,'v17 battle create');BL.Battle.play(0);if(BL.Battle.current){assert(BL.Battle.invariant().ok,'v17 battle ownership');BL.Battle.retire();}
const migrated=BL.Store.mergeDefaults({version:16,deck:[...D.DEFAULT_DECK],unlockedCards:{},unlockedRelics:{}});assert(migrated.version===30,'v17->v20 migration failed');
console.log('PASS expansion17_systems.test.js');
