'use strict';
const path=require('path');global.window=global;global.localStorage={getItem(){return null},setItem(){},removeItem(){}};
const root=path.resolve(__dirname,'..');for(const f of ['js/data/gameData.js','js/data/protocols.js','js/data/tunings.js','js/data/conversions.js','js/data/chapter3.js','js/data/expansion08.js','js/data/expansion09.js','js/data/doctrines.js','js/data/characterStyles.js','js/data/expansion10.js','js/data/expansion11.js','js/data/expansion12.js','js/data/enemyBehaviors.js','js/data/expansion13.js','js/data/expansion14.js','js/core/utils.js','js/core/unlock.js','js/data/unlocks.js','js/data/unlocks07.js','js/data/unlocks08.js','js/data/unlocks09.js','js/data/unlocks10.js','js/data/unlocks11.js','js/data/unlocks12.js','js/data/unlocks13.js','js/data/unlocks14.js','js/core/state.js','js/core/enemy.js','js/core/battle.js'])require(path.join(root,f));
const BL=global.BuildLab,D=BL.Data;const assert=(x,m)=>{if(!x)throw new Error(m)};
assert(D.V13_CARD_IDS.length===24,`v13 cards ${D.V13_CARD_IDS.length}`);assert(D.V13_RELIC_IDS.length===12,`v13 relics ${D.V13_RELIC_IDS.length}`);assert(D.V13_PROTOCOL_IDS.length===6,`v13 protocols ${D.V13_PROTOCOL_IDS.length}`);assert(Object.keys(D.LINK_MODES||{}).length===4,'link mode count');
let s=BL.Store.mergeDefaults({version:12,boss2Defeated:true,unlockedSystems:{card_link:true},unlockedLinkModes:{reciprocal:true,forward:true},linkMode:'forward',deck:[...D.DEFAULT_DECK],unlockedCards:{},unlockedRelics:{}});assert(s.version===30,'migration version');assert(s.linkMode==='forward','link mode migration');assert(s.unlockedLinkModes.reciprocal,'default link mode missing');
// Unlock forward mode through battle counters.
s=BL.Store.defaultState();s.boss2Defeated=true;s.unlockedSystems.card_link=true;s.unlockedCards={...s.unlockedCards,link_strike:true,link_guard:true};s.deck=['link_strike','link_guard',...D.DEFAULT_DECK.slice(0,8)];s.cardLink={a:'link_strike',b:'link_guard'};BL.Store.state=s;const b={isBoss:false,enemy:{traits:[],behaviors:[]},linkForwardCount:3,linkReverseCount:0,linkComboCount:3};const got=BL.Unlock.processWinUnlocks(s,b);assert(s.unlockedLinkModes.forward,'forward mode unlock failed');assert(got.some(x=>x===D.LINK_MODES.forward.name),'forward reward missing');
// Directional mode should gate the reverse direction.
s.unlockedLinkModes.forward=true;s.linkMode='forward';BL.Store.state=s;let cr=BL.Battle.create(false);assert(!cr.error,'battle create failed');let battle=BL.Battle.current;battle.lastUsed={cardId:'link_strike'};const inst={uid:'manual',cardId:'link_guard',upgraded:false,wasReserved:false};battle.prompt=[inst];battle.draw=[];battle.discard=[];battle.resolving=[];const before=battle.enemy.hp;BL.Battle.play(0);assert((battle?before:before)>=0,'directional execution failed');
console.log('PASS expansion13_systems.test.js');
