#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
find "$ROOT/js" -name '*.js' -print0 | xargs -0 -n1 node --check
node "$ROOT/tests/smoke.test.js"
node "$ROOT/tests/content_balance.test.js"
node "$ROOT/tests/effect_coverage.test.js"
node "$ROOT/tests/balance22_audit.test.js"
node "$ROOT/tests/expansion23_systems.test.js"
node "$ROOT/tests/expansion24_systems.test.js"
node "$ROOT/tests/expansion26_systems.test.js"
node "$ROOT/tests/expansion27_systems.test.js"
node "$ROOT/tests/expansion28_balance_audit.test.js"
node "$ROOT/tests/expansion29_adaptive.test.js"
node "$ROOT/tests/expansion30_growth.test.js"
node "$ROOT/tests/boss_balance.test.js"
node "$ROOT/tests/boss_reward_integration.test.js"
node "$ROOT/tests/chapter2_systems.test.js"
node "$ROOT/tests/chapter3_systems.test.js"
node "$ROOT/tests/expansion08_systems.test.js"
node "$ROOT/tests/boss2_balance.test.js"
node "$ROOT/tests/expansion09_systems.test.js"
node "$ROOT/tests/expansion10_systems.test.js"
node "$ROOT/tests/expansion11_systems.test.js"
node "$ROOT/tests/expansion12_systems.test.js"
node "$ROOT/tests/expansion13_systems.test.js"
node "$ROOT/tests/expansion14_systems.test.js"
node "$ROOT/tests/expansion17_systems.test.js"
node "$ROOT/tests/expansion18_systems.test.js"
node "$ROOT/tests/expansion19_systems.test.js"
node "$ROOT/tests/expansion20_systems.test.js"
node "$ROOT/tests/boss4_reward_integration.test.js"
node "$ROOT/tests/reset_controls.test.js"
node "$ROOT/tests/boss3_balance.test.js"
node "$ROOT/tests/boss4_balance.test.js"
node "$ROOT/tests/static_ui.test.js"
node "$ROOT/tests/system_guide.test.js"
node "$ROOT/tests/guide_detail.test.js"
node "$ROOT/tests/web_deploy.test.js"
node "$ROOT/tests/mobile_ui.test.js"
node "$ROOT/tests/modal_overflow.test.js"
node "$ROOT/tests/alchemy.test.js"
echo "All checks passed."
