'use strict';
(function(){
  const BL=window.BuildLab,D=BL.Data,U=BL.Util; BL.UI=BL.UI||{};
  const isMobile=()=>!!(document.body?.classList.contains('mobile-ui')||(window.matchMedia&&window.matchMedia('(max-width: 760px)').matches));
  function setupPager(area,pager,count){
    if(!pager)return; if(!isMobile()||count<=1){pager.innerHTML='';return;}
    pager.innerHTML=`<span class="mobile-pager-count">1 / ${count}</span><div class="mobile-pager-dots">${Array.from({length:count},(_,i)=>`<button type="button" aria-label="${i+1}枚目" data-page="${i}" class="${i===0?'active':''}"></button>`).join('')}</div>`;
    const dots=[...pager.querySelectorAll('[data-page]')],label=pager.querySelector('.mobile-pager-count'),cards=[...area.querySelectorAll('.battle-card')];
    let raf=0;const update=()=>{raf=0;if(!cards.length)return;const center=area.getBoundingClientRect().left+area.clientWidth/2;let best=0,dist=Infinity;cards.forEach((c,i)=>{const r=c.getBoundingClientRect(),d=Math.abs((r.left+r.right)/2-center);if(d<dist){dist=d;best=i;}});dots.forEach((d,i)=>d.classList.toggle('active',i===best));label.textContent=`${best+1} / ${count}`;};
    area.onscroll=()=>{if(!raf)raf=requestAnimationFrame(update);};dots.forEach((d,i)=>d.onclick=()=>cards[i]?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'}));requestAnimationFrame(update);
  }
  function renderBattle(){
    const b=BL.Battle.current,panel=document.getElementById('battlePanel');if(!b){panel.classList.add('hidden');const pg=document.getElementById('mobileBattlePager');if(pg)pg.innerHTML='';return;}panel.classList.remove('hidden');const s=BL.Store.state,c=D.CHARACTERS[s.character],style=D.getCharacterStyle?.(s,s.character),mobile=isMobile();
    document.getElementById('battlePlayerName').textContent=`${c.name}${style?`［${style.name}］`:''}`;document.getElementById('battleEnemyName').textContent=b.enemy.name;document.getElementById('turnNumber').textContent=b.turn;document.getElementById('playerHpText').textContent=`HP ${U.fmt(b.player.hp)} / ${U.fmt(b.player.maxHp)}　防御 ${U.fmt(b.player.block)}`;document.getElementById('enemyHpText').textContent=`HP ${U.fmt(b.enemy.hp)} / ${U.fmt(b.enemy.maxHp)}　防御 ${U.fmt(b.enemy.def)}${b.enemy.block?`　障壁 ${U.fmt(b.enemy.block)}`:''}`;document.getElementById('playerHpFill').style.width=`${100*Math.max(0,b.player.hp)/b.player.maxHp}%`;document.getElementById('enemyHpFill').style.width=`${100*Math.max(0,b.enemy.hp)/b.enemy.maxHp}%`;document.getElementById('playerStatus').textContent=s.character==='tank'?`強化済み ${BL.Battle.upgradedCount()}枚`:' ';document.getElementById('enemyStatus').textContent=`${BL.Battle.statusText()} / 再生 ${b.enemy.regen||0} / 耐性 ${b.enemy.resist||0}%${b.enemy.behaviors?.length?` / 複合挙動 ${b.enemy.behaviors.map(id=>D.ENEMY_BEHAVIORS[id]?.name||id).join('・')}`:''}`;document.getElementById('enemyIntent').textContent=b.isBoss?BL.Battle.bossIntentText():`次の敵行動：攻撃 ${U.fmt(BL.Battle.enemyAttackValue())} × ${BL.Battle.actionCountPreview()}`;
    BL.UI.renderAlchemyBattle?.(b);
    const area=document.getElementById('promptCards');area.innerHTML='';const center=Math.floor((b.prompt.length-1)/2);
    b.prompt.forEach((x,i)=>{let cc=D.CARDS[x.cardId];if(D.resolveDualFaceCard)cc=D.resolveDualFaceCard(x,b,s);if(D.resolveMultiStageCard)cc=D.resolveMultiStageCard(x,b,s);if(D.resolveAdaptiveCard)cc=D.resolveAdaptiveCard(cc,x,b,s);const el=document.createElement(mobile?'div':'button');el.className='battle-card'+(i===center?' center':'')+(mobile?' touch-card':'');const tune=s.cardTunings?.[x.cardId],link=s.cardLink||{},linked=link.a===x.cardId||link.b===x.cardId,adaptiveLabel=cc.adaptiveLabel?`<div class="upgrade">解析：${cc.adaptiveLabel}</div>`:'',stageLabel=cc.stageLabel?`<div class="upgrade">成長段階：${cc.stageLabel}</div>`:'';const roleLabel=cc.stageRole?`<div class="upgrade">成長方針：${cc.stageRole}${cc.holdable?'（維持可能）':''}</div>`:'';const branchLabel=cc.branchLabel?`<div class="upgrade">確定分岐：${cc.branchLabel}</div>`:'';const cardBody=`${i===center?'<div class="center-mark">CENTER SLOT</div>':''}<div class="title">${cc.name}</div>${x.upgraded?'<div class="upgrade">強化版</div>':''}${tune?`<div class="upgrade">${D.TUNINGS[tune].name}</div>`:''}${linked?'<div class="upgrade">LINK</div>':''}${adaptiveLabel}${stageLabel}${roleLabel}${branchLabel}<div class="desc">${cc.desc}</div><div class="tags">${cc.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div>`;
      if(mobile){
        const canSwap=BL.Unlock.hasSystem(s,'prompt_control')&&i!==center&&(s.relics.includes('phase_exchanger')||b.reorderNext),canRedraw=BL.Unlock.hasSystem(s,'prompt_control')&&((s.relics.includes('reroll_terminal')&&!b.relicRedrawUsed)||b.redrawNext);
        el.innerHTML=`${cardBody}<div class="mobile-card-actions"><button type="button" class="primary" data-card-action="play">使用</button>${canSwap?'<button type="button" class="ghost" data-card-action="swap">中央交換</button>':''}${canRedraw?'<button type="button" class="ghost" data-card-action="redraw">再提示</button>':''}</div>`;
        el.querySelector('[data-card-action="play"]').onclick=e=>{e.stopPropagation();BL.Battle.play(i);};const sw=el.querySelector('[data-card-action="swap"]');if(sw)sw.onclick=e=>{e.stopPropagation();BL.Battle.swapWithCenter(i);};const rd=el.querySelector('[data-card-action="redraw"]');if(rd)rd.onclick=e=>{e.stopPropagation();BL.Battle.redraw(i);};
      }else{
        el.innerHTML=cardBody;el.onclick=()=>BL.Battle.play(i);if(s.bossDefeated&&i!==center)el.ondblclick=e=>{e.preventDefault();BL.Battle.swapWithCenter(i);};if(s.bossDefeated)el.oncontextmenu=e=>{e.preventDefault();BL.Battle.redraw(i);};
      }
      area.appendChild(el);
    });
    document.getElementById('promptHelp').textContent=mobile?(s.bossDefeated?'提示カード — 横にスワイプ / カード下の操作ボタンを使用':'提示カード — 横にスワイプして「使用」をタップ'):(s.bossDefeated?'提示カード — クリックで使用 / ダブルクリックで中央交換（条件時）/ 右クリックで再提示（条件時）':'提示カード — 1枚を選択');setupPager(area,document.getElementById('mobileBattlePager'),b.prompt.length);document.getElementById('battleLog').innerHTML=b.log.slice(-16).map(x=>`<div>${x}</div>`).join('');const inv=BL.Battle.invariant(),debug=document.getElementById('battleInvariant');debug.textContent=`CARD CHECK ${inv.unique}/${inv.expected}`;debug.classList.toggle('bad',!inv.ok);if(!inv.ok)console.error('Card ownership invariant failed',inv,b);
  }
  BL.UI.renderBattle=renderBattle;
})();
